'use strict';

/**
 * AI Tool Registry
 *
 * Each entry defines publicly observable patterns used to detect
 * AI coding tool involvement in git commits. All patterns are
 * sourced from publicly documented behaviors, official tool
 * documentation, and publicly visible commit histories.
 */
const TOOLS = [
  {
    id: 'copilot',
    name: 'GitHub Copilot',
    // Verified: Copilot Coding Agent uses this trailer
    // Source: GitHub docs, public commits
    coAuthorEmails: ['copilot@github.com'],
    coAuthorPatterns: [/copilot/i],
    commitPatterns: [/generated by copilot/i, /copilot/i],
    fileHeaders: [/generated by.*copilot/i, /github copilot/i],
    configKeys: ['copilot.enabled']
  },
  {
    id: 'cursor',
    name: 'Cursor',
    // Verified: Cursor agent adds this trailer
    // Source: Cursor docs, community reports
    coAuthorEmails: ['cursor@cursor.sh'],
    coAuthorPatterns: [/cursor/i],
    commitPatterns: [/via cursor/i, /cursor/i],
    fileHeaders: [/@cursor-generated/i, /cursor/i],
    configKeys: []
  },
  {
    id: 'claude-code',
    name: 'Claude Code',
    // Verified: Claude Code adds co-author trailer by default
    // Source: Anthropic docs, public commits
    coAuthorEmails: ['noreply@anthropic.com'],
    coAuthorPatterns: [/claude/i, /anthropic/i],
    commitPatterns: [/claude/i, /anthropic/i],
    fileHeaders: [/claude/i],
    configKeys: []
  },
  {
    id: 'codeium',
    name: 'Codeium',
    // Community reported patterns
    coAuthorEmails: [],
    coAuthorPatterns: [/codeium/i],
    commitPatterns: [/codeium/i],
    fileHeaders: [/codeium/i],
    configKeys: []
  },
  {
    id: 'aider',
    name: 'Aider',
    // Verified: aider uses --attribute-co-authored-by flag
    // Source: aider.chat docs
    coAuthorEmails: ['aider@aider.chat', 'noreply@aider.chat'],
    coAuthorPatterns: [/aider/i],
    commitPatterns: [/aider/i],
    fileHeaders: [/aider/i],
    configKeys: []
  },
  {
    id: 'codex-cli',
    name: 'OpenAI Codex CLI',
    // Community reported patterns
    coAuthorEmails: [],
    coAuthorPatterns: [/codex/i, /openai/i],
    commitPatterns: [/codex/i],
    fileHeaders: [/codex/i, /openai codex/i],
    configKeys: []
  },
  {
    id: 'gemini-code-assist',
    name: 'Gemini Code Assist',
    // Community reported patterns
    coAuthorEmails: [],
    coAuthorPatterns: [/gemini/i],
    commitPatterns: [/gemini.*code.*assist/i],
    fileHeaders: [],
    configKeys: []
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    // Community reported patterns
    coAuthorEmails: [],
    coAuthorPatterns: [/windsurf/i],
    commitPatterns: [/windsurf/i],
    fileHeaders: [/windsurf/i],
    configKeys: []
  },
  {
    id: 'tabnine',
    name: 'Tabnine',
    // Community reported patterns
    coAuthorEmails: [],
    coAuthorPatterns: [/tabnine/i],
    commitPatterns: [/tabnine/i],
    fileHeaders: [/tabnine/i],
    configKeys: []
  },
  {
    id: 'devin',
    name: 'Devin',
    // Verified: Devin AI integration bot
    // Source: public GitHub commits from Devin
    coAuthorEmails: ['devin-ai-integration[bot]@users.noreply.github.com'],
    coAuthorPatterns: [/devin/i],
    commitPatterns: [/devin/i],
    fileHeaders: [],
    configKeys: []
  },
  {
    id: 'openhands',
    name: 'OpenHands',
    // Verified: OpenHands agent uses this email
    // Source: OpenHands docs on GitHub
    coAuthorEmails: ['openhands@all-hands.dev'],
    coAuthorPatterns: [/openhands/i, /all.hands/i],
    commitPatterns: [/openhands/i, /all.hands/i],
    fileHeaders: [],
    configKeys: []
  },
  {
    id: 'amazon-q',
    name: 'Amazon Q Developer',
    // Verified: Amazon Q (formerly CodeWhisperer) adds attribution
    // Source: AWS docs, public commits
    coAuthorEmails: [],
    coAuthorPatterns: [/amazon.q/i, /codewhisperer/i],
    commitPatterns: [/amazon.q/i, /codewhisperer/i],
    fileHeaders: [/amazon.q/i, /codewhisperer/i],
    configKeys: []
  },
  {
    id: 'jetbrains-ai',
    name: 'JetBrains AI Assistant',
    // Community reported patterns
    // Source: JetBrains docs, IDE telemetry headers
    coAuthorEmails: [],
    coAuthorPatterns: [/jetbrains.*ai/i],
    commitPatterns: [/jetbrains.*ai/i, /ai.*assistant/i],
    fileHeaders: [/jetbrains/i],
    configKeys: []
  },
  {
    id: 'sourcegraph-cody',
    name: 'Sourcegraph Cody',
    // Verified: Cody adds attribution markers
    // Source: Sourcegraph docs, public commits
    coAuthorEmails: ['cody@sourcegraph.com'],
    coAuthorPatterns: [/cody/i, /sourcegraph/i],
    commitPatterns: [/cody/i, /sourcegraph/i],
    fileHeaders: [/sourcegraph.*cody/i],
    configKeys: []
  },
  {
    id: 'replit-ai',
    name: 'Replit AI',
    // Community reported patterns
    // Source: Replit platform, public repos
    coAuthorEmails: [],
    coAuthorPatterns: [/replit/i],
    commitPatterns: [/replit.*ai/i, /replit.*agent/i],
    fileHeaders: [/replit/i],
    configKeys: []
  },
  {
    id: 'cline',
    name: 'Cline',
    // Verified: Cline (formerly Claude Dev) adds co-author trailers
    // Source: Cline GitHub, public commits
    coAuthorEmails: ['cline@cline.bot'],
    coAuthorPatterns: [/cline/i],
    commitPatterns: [/cline/i, /claude.dev/i],
    fileHeaders: [],
    configKeys: []
  },
  {
    id: 'continue',
    name: 'Continue',
    // Community reported patterns
    // Source: Continue.dev docs
    coAuthorEmails: [],
    coAuthorPatterns: [/continue/i],
    commitPatterns: [/continue\.dev/i],
    fileHeaders: [/continue/i],
    configKeys: ['continue.enabled']
  },
  {
    id: 'gpt-engineer',
    name: 'GPT Engineer',
    // Community reported patterns
    // Source: public repos created by GPT Engineer
    coAuthorEmails: ['gpt-engineer@lovable.dev'],
    coAuthorPatterns: [/gpt.engineer/i],
    commitPatterns: [/gpt.engineer/i],
    fileHeaders: [/gpt.engineer/i],
    configKeys: []
  },
  {
    id: 'bolt',
    name: 'Bolt',
    // Community reported patterns
    // Source: StackBlitz Bolt, public repos
    coAuthorEmails: [],
    coAuthorPatterns: [/bolt/i],
    commitPatterns: [/bolt\.new/i, /stackblitz.*bolt/i],
    fileHeaders: [/bolt/i],
    configKeys: []
  }
];

module.exports = { TOOLS };
