'use strict';

const yaml = require('js-yaml');
const fs = require('fs');
const path = require('path');

const HEADER_COMMENT = `# AI Attestation
# https://oss.korext.com/ai-attestation
#
# This file tracks AI generated code in this repository.
# Generated by @korext/ai-attestation
`;

/**
 * Build an attestation data object from detection results.
 */
function buildAttestation(repoInfo, detection) {
  const now = new Date().toISOString();
  const tools = Object.values(detection.tools)
    .filter(t => t.commitCount > 0)
    .sort((a, b) => b.commitCount - a.commitCount)
    .map(t => ({
      name: t.name,
      identifier: t.id,
      first_seen: t.firstSeen ? t.firstSeen.split('T')[0] : null,
      last_seen: t.lastSeen ? t.lastSeen.split('T')[0] : null,
      commit_count: t.commitCount
    }));

  return {
    schema: 'https://oss.korext.com/ai-attestation/schema',
    version: '1.0',
    repo: {
      owner: repoInfo.owner,
      name: repoInfo.name,
      url: repoInfo.url
    },
    generated: now,
    range: {
      from: detection.range.from || now,
      to: detection.range.to || now,
      commits: detection.totalCommits
    },
    ai: {
      assisted_commits: detection.aiAssistedCommits,
      percentage: detection.percentage,
      tools: tools,
      detection_methods: detection.detectionMethods
    },
    governance: {
      engine: null,
      last_scan: null,
      result: null,
      score: null,
      packs: [],
      findings: {
        critical: 0,
        high: 0,
        medium: 0,
        low: 0
      },
      proof_bundle_url: null,
      proof_bundle_count: 0
    },
    policy: {
      ai_code_requires_review: false,
      minimum_governance_score: null,
      mandatory_packs: [],
      block_unscanned_ai_code: false
    }
  };
}

/**
 * Write attestation data to .ai-attestation.yaml
 */
function writeAttestation(repoPath, data) {
  const filePath = path.join(repoPath, '.ai-attestation.yaml');
  const yamlStr = yaml.dump(data, {
    indent: 2,
    lineWidth: -1,
    noRefs: true,
    sortKeys: false,
    quotingType: '"',
    forceQuotes: false
  });

  fs.writeFileSync(filePath, HEADER_COMMENT + '\n' + yamlStr, 'utf8');
  return filePath;
}

/**
 * Read existing attestation file.
 */
function readAttestation(repoPath) {
  const filePath = path.join(repoPath, '.ai-attestation.yaml');
  if (!fs.existsSync(filePath)) {
    return null;
  }
  const content = fs.readFileSync(filePath, 'utf8');
  return yaml.load(content);
}

/**
 * Update an existing attestation with new commit data.
 * Used by the git hook for incremental updates.
 */
function updateAttestation(repoPath, commitMessage, detectedTools) {
  let data = readAttestation(repoPath);
  if (!data) return null;

  const now = new Date().toISOString();

  // Increment total commits
  data.range.commits = (data.range.commits || 0) + 1;
  data.range.to = now;
  data.generated = now;

  if (detectedTools.length > 0) {
    // Increment AI assisted commits
    data.ai.assisted_commits = (data.ai.assisted_commits || 0) + 1;

    // Update tools
    for (const tool of detectedTools) {
      const existing = data.ai.tools.find(t => t.identifier === tool.id);
      if (existing) {
        existing.commit_count = (existing.commit_count || 0) + 1;
        existing.last_seen = now.split('T')[0];
      } else {
        data.ai.tools.push({
          name: tool.name,
          identifier: tool.id,
          first_seen: now.split('T')[0],
          last_seen: now.split('T')[0],
          commit_count: 1
        });
      }

      // Update detection methods
      if (!data.ai.detection_methods.includes(tool.method)) {
        data.ai.detection_methods.push(tool.method);
      }
    }

    // Recalculate percentage
    data.ai.percentage = data.range.commits > 0
      ? Math.round((data.ai.assisted_commits / data.range.commits) * 1000) / 10
      : 0;
  }

  writeAttestation(repoPath, data);
  return data;
}

module.exports = {
  buildAttestation,
  writeAttestation,
  readAttestation,
  updateAttestation,
  HEADER_COMMENT
};
